---
name: Deploy Collection - kenmoini.redfish

# Trigger the workflow however you prefer
on:
  push:
    # tags:
    #   - v*
    paths:
      - kenmoini/redfish/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          collection_dir: 'kenmoini/redfish'